/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData doc = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData database = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData params = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData note = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData attach = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData database_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData license = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chart_bars = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
}
